### ISSUE TITLE
App panic on user

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/multisig#32]
Michael's push panicked:
```
multisig tx push ../Downloads/unsigned4.json cosmos icf-fc
panic: interface conversion: interface {} is nil, not []interface {}
goroutine 1 [running]:
main.parseDenomFromJson(0xc0000d4900, 0x699, 0x899, 0x0, 0x0, 0x0, 0x0)
	/Users/niedm/multisig/util.go:114 +0x286
main.cmdPush(0x1cd8100, 0xc0002b23c0, 0x3, 0x3, 0x0, 0x0)
	/Users/niedm/multisig/main.go:342 +0x145
[github.com/spf13/cobra.(*Command).execute(0x1cd8100](http://github.com/spf13/cobra.(*Command).execute(0x1cd8100), 0xc0002b2390, 0x3, 0x3, 0x1cd8100, 0xc0002b2390)
	/Users/niedm/goApps/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
[github.com/spf13/cobra.(*Command).ExecuteC(0x1cd7480](http://github.com/spf13/cobra.(*Command).ExecuteC(0x1cd7480), 0x0, 0x0, 0x0)
	/Users/niedm/goApps/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
	/Users/niedm/goApps/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/Users/niedm/multisig/main.go:45 +0x2d
macbook-pro:multisig niedm$
```

unsigned4.json:
```
{
  "body": {
    "messages": [
      {
        "@type": "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
        "delegator_address": "cosmos1z8mzakma7vnaajysmtkwt4wgjqr2m84tzvyfkz",
        "validator_address": "cosmosvaloper14kn0kk33szpwus9nh8n87fjel8djx0y070ymmj"
      },
      {
        "@type": "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
        "delegator_address": "cosmos1z8mzakma7vnaajysmtkwt4wgjqr2m84tzvyfkz",
        "validator_address": "cosmosvaloper1hjct6q7npsspsg3dgvzk3sdf89spmlpfdn6m9d"
      },
      {
        "@type": "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
        "delegator_address": "cosmos1z8mzakma7vnaajysmtkwt4wgjqr2m84tzvyfkz",
        "validator_address": "cosmosvaloper1clpqr4nrk4khgkxj78fcwwh6dl3uw4epsluffn"
      },
      {
        "@type": "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
        "delegator_address": "cosmos1z8mzakma7vnaajysmtkwt4wgjqr2m84tzvyfkz",
        "validator_address": "cosmosvaloper1ehkfl7palwrh6w2hhr2yfrgrq8jetgucudztfe"
      },
      {
        "@type": "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
        "delegator_address": "cosmos1z8mzakma7vnaajysmtkwt4wgjqr2m84tzvyfkz",
        "validator_address": "cosmosvaloper1kgddca7qj96z0qcxr2c45z73cfl0c75p7f3s2e"
      }
    ],
    "memo": "",
    "timeout_height": "0",
    "extension_options": [],
    "non_critical_extension_options": []
  },
  "auth_info": {
    "signer_infos": [],
    "fee": {
      "amount": [
        {
          "denom": "uatom",
          "amount": "10000"
        }
      ],
      "gas_limit": "1200000",
      "payer": "",
      "granter": ""
    }
  },
  "signatures": []
}
```

Possibly the file has some issues, but we still shouldn't panic.

**Comment by andynog** [comment]
Related to #26
